import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
  // resources/js-debug is Microsoft's vendored adapter build (12.4), not ours.
  // src/renderer/public/mojo holds the transpiled Chromium Mojo bindings, which
  // are machine-generated by scripts/gen-mojo-bindings.mjs (source of truth is
  // the .mojom, not this artifact) — same reason .prettierignore skips it.
  {
    ignores: ['out/', 'node_modules/', 'dist/', 'resources/js-debug/', 'src/renderer/public/mojo/']
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/renderer/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules
  },
  // Project-wide defaults. These come BEFORE the file-specific overrides below
  // so the overrides win (flat config is last-match-wins); putting them after
  // would silently re-enable explicit-function-return-type for the *.mjs / *.cjs
  // files that opt out of it.
  {
    rules: {
      '@typescript-eslint/explicit-function-return-type': ['warn', { allowExpressions: true }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }]
    }
  },
  {
    files: ['scripts/**/*.mjs', 'electron.vite.config.ts'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
        // Present inside page.evaluate callbacks, which run in the renderer.
        document: 'readonly'
      }
    },
    rules: { '@typescript-eslint/explicit-function-return-type': 'off' }
  },
  {
    files: ['resources/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: { require: 'readonly', process: 'readonly', module: 'readonly' }
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off'
    }
  },
  prettier
)
